using System.Buffers.Binary;
using System.Security.Cryptography;

namespace KeystrokeApp.Services;

public enum LicenseTier : byte
{
    Free = 0,
    Pro = 1
}

public sealed record LicenseInfo(
    LicenseTier Tier,
    long KeyId,
    DateTimeOffset IssuedAt,
    bool IsValid);

/// <summary>
/// Validates license keys using an embedded ECDSA P-256 public key.
/// Keys are signed offline with the private key (never shipped).
/// Validation is fully offline — no network calls.
/// </summary>
public static class LicenseService
{
    // ECDSA P-256 public key coordinates (32 bytes each).
    // Generated by tools/KeystrokeKeyGen — private key stays offline.
    private static readonly byte[] PublicKeyX = [0x39, 0x35, 0xAA, 0x4F, 0x3F, 0xCE, 0x54, 0x4B, 0xE6, 0xA1, 0xB2, 0xA9, 0xC2, 0xE7, 0x86, 0xC1, 0x7A, 0xE2, 0x10, 0xC4, 0xCA, 0x06, 0x44, 0x8C, 0x66, 0xA6, 0x17, 0x11, 0x3E, 0x0E, 0x53, 0x6C];
    private static readonly byte[] PublicKeyY = [0x56, 0x3F, 0x53, 0x25, 0x06, 0x86, 0x2B, 0x57, 0xC1, 0x02, 0xFC, 0x19, 0xAD, 0x33, 0xE2, 0x7C, 0xA2, 0x72, 0xCE, 0x12, 0x1F, 0xDD, 0xE0, 0x9F, 0xEA, 0xDF, 0x44, 0x7F, 0x06, 0x21, 0xAF, 0x79];

    private const string KeyPrefix = "KS-";
    private const int PayloadLength = 14;   // version(1) + tier(1) + keyId(8) + timestamp(4)
    private const int SignatureLength = 64;  // ECDSA P-256 DER-decoded r‖s
    private const int TotalRawLength = PayloadLength + SignatureLength; // 78 bytes

    /// <summary>
    /// Validates a license key string. Fully offline — decodes the key,
    /// verifies the ECDSA signature against the embedded public key,
    /// and parses the payload.
    /// </summary>
    public static LicenseInfo Validate(string? licenseKey)
    {
        if (string.IsNullOrWhiteSpace(licenseKey))
            return new LicenseInfo(LicenseTier.Free, 0, default, false);

        var raw = licenseKey.Trim();
        if (!raw.StartsWith(KeyPrefix, StringComparison.OrdinalIgnoreCase))
            return new LicenseInfo(LicenseTier.Free, 0, default, false);

        try
        {
            var base32Part = raw[KeyPrefix.Length..].Replace("-", "");
            var bytes = Base32.Decode(base32Part);
            if (bytes == null || bytes.Length != TotalRawLength)
                return new LicenseInfo(LicenseTier.Free, 0, default, false);

            var payload = bytes.AsSpan(0, PayloadLength);
            var signature = bytes.AsSpan(PayloadLength, SignatureLength);

            if (!VerifySignature(payload, signature))
                return new LicenseInfo(LicenseTier.Free, 0, default, false);

            // Parse payload fields
            var version = payload[0];
            if (version != 1)
                return new LicenseInfo(LicenseTier.Free, 0, default, false);

            var tier = (LicenseTier)payload[1];
            var keyId = BinaryPrimitives.ReadInt64BigEndian(payload.Slice(2, 8));
            var timestamp = BinaryPrimitives.ReadUInt32BigEndian(payload.Slice(10, 4));
            var issuedAt = DateTimeOffset.FromUnixTimeSeconds(timestamp);

            return new LicenseInfo(tier, keyId, issuedAt, true);
        }
        catch
        {
            return new LicenseInfo(LicenseTier.Free, 0, default, false);
        }
    }

    /// <summary>
    /// Convenience method: decrypts the stored license key via DPAPI,
    /// validates it, and returns true if it's a valid Pro license.
    /// </summary>
    public static bool IsPro(string? encryptedLicenseKey)
    {
        var plaintext = ApiKeyEncryption.Decrypt(encryptedLicenseKey);
        var info = Validate(plaintext);
        return info.IsValid && info.Tier == LicenseTier.Pro;
    }

    private static bool VerifySignature(ReadOnlySpan<byte> payload, ReadOnlySpan<byte> signature)
    {
        // All-zero public key means keygen hasn't been run yet — reject everything.
        if (IsAllZero(PublicKeyX))
            return false;

        using var ecdsa = ECDsa.Create(new ECParameters
        {
            Curve = ECCurve.NamedCurves.nistP256,
            Q = new ECPoint
            {
                X = PublicKeyX,
                Y = PublicKeyY
            }
        });

        return ecdsa.VerifyData(payload, signature, HashAlgorithmName.SHA256);
    }

    private static bool IsAllZero(byte[] data)
    {
        foreach (var b in data)
            if (b != 0)
                return false;
        return true;
    }
}
